config-version = 2

# Startup & Integration
after-startup-command = [
  'exec-and-forget sketchybar',
  'exec-and-forget borders active_color=0xffcba6f7 inactive_color=0xff313244 width=8.0 hidpi=on',
]
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

# General Settings
start-at-login = true
auto-reload-config = true
on-mode-changed = []

# Normalization & Layout
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = false
key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
persistent-workspaces = ['1', '2', '3', '4', '5', '6', '7', '8', '9']

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]
# Layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-f = 'layout floating tiling'
alt-r = 'flatten-workspace-tree'

# Focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move Windows
alt-ctrl-h = 'move left'
alt-ctrl-j = 'move down'
alt-ctrl-k = 'move up'
alt-ctrl-l = 'move right'

# Join Splits
alt-shift-h = 'join-with left'
alt-shift-j = 'join-with down'
alt-shift-k = 'join-with up'
alt-shift-l = 'join-with right'

# Resize
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

# Workspaces Navigation
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

# Move Window to Workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

# Workspace & Monitor Extras
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-s = 'exec-and-forget screencapture -i -c'

# Service Mode
alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

[[on-window-detected]]
if = 'true'
run = ['exec-and-forget sketchybar --trigger space_windows_change']
