# Terminal & True Color
set -g default-terminal "tmux-256color"
set-option -sa terminal-features ',xterm-256color:RGB'
set -g mouse on
set -g history-limit 10000

# Base Indexing & Window Renaming
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
set-option -g automatic-rename on
set-option -g automatic-rename-format "#{?pane_in_mode,[tmux],#{pane_current_command}}"

# Prefix (Ctrl+a)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Splits & Window Creation 
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Navigation
bind h previous-window
bind l next-window
bind Space last-window

# Vi Copy Mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Theme (Catppuccin Mocha)
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"

# Status Bar Layout
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_session}"

# TPM Initialization 
run '~/.config/tmux/plugins/tpm/tpm'
